### ISSUE TITLE
build failure due to undocumented dependency

### ISSUE THREAD

**Issue by mc0e** [garywiz/chaperone#1]
On both ubuntu:14.04 and debian:jessie, installing chaperone requires both `python3-pip` and also the `build-essential` and `python3-dev` packages which python3-pip recommends, but does not require.

As a result, this fails:

    from ubuntu:14.04

    ENV DEBIAN_FRONTEND noninteractive
    ENV DEBIAN_PRIORITY critical
    ENV DEBCONF_NOWARNINGS yes

    RUN apt-get update \
        && apt-get upgrade -y

    RUN apt-get install --no-install-recommends -y \
        python3-pip

    RUN pip3 install chaperone

In the interests of building small containers, using `apt-get --no-install-recommends -y` is typically a good idea, but here it means that the other two packages need to be explicitly installed (or `apt-get install -y python3-pip` needs to be in a separate `RUN` statement to other packages that will be installed, which uses an extra filesystem layer for little advantage).

Reasonable people could argue, but consider stating the dependency in the README instructions.  And if not, then at least this issue might point out the problem for someone.

**Comment by garywiz** [comment]
I'll add a section to the README describing the situation.  The install instructions are pretty simple, and if they are followed as written, they should work as described.  But, adding --no-install-recommends does indeed cause the problem as indicated and I'll make that clear.  

You may want to take a look at the technique I use here: https://github.com/garywiz/chaperone-docker/blob/master/baseimage/Makefile

Essentially, I did not want the chaperone-baseimage to include the build-essentials (gnu toolchain etc) for exactly the reasons you describe.   So, I the Makefile shown above runs one isolated throw-away container specifically to create the setproctitle binary, then bundles it into the final build so that a binary-only package is created and no build-essential package is required.  I do the same thing for the chaperone-alpinebase image to the image down to about 55MB.

I'm considering dropping the setproctitle module entirely, which does not really add much value to the functionality at all, and that would eliminate any build toolchain dependencies.  Or, at a minimum, I may make it optional so that it will only install if the toolchain is already present.

**Comment by garywiz** [comment]
This problem will no longer occur in 0.2.24, which is now published here and on PyPi.   In the case where `--no-install-recommends` is used, Chaperone will simply disable the functionality which would require the `gcc` toolchain.  At present, the only functionality that will be missing is the "friendly process title" that Chaperone usually sets on `ps` lists.  This may affect any automated tests or scripts which rely upon `ps` output, but I believe this is a minor issue.
