### ISSUE TITLE
How should I call a runtime startup script?

### ISSUE THREAD

**Issue by mc0e** [garywiz/chaperone#2]
It's common practice in docker containers to have some script that gets run at run time to do things like take values from environment values and construct the odd config file with them before the main daemon process(es) get run.  This commonly gets shoe-horned into the CMD or ENTRYPOINT directive.

It seems in keeping with the philosophy of chaperone that this should probably hang off the chaperone config, and also I suspect not doing it that way would mean that the wrong process would be PID 1, and responsible for zombies.  I'm still just finding my way here, but I'm not seeing a really elegant way to do it with chaperone.  What am I missing?

Maybe I could create a one-shot service, and set up some before/after rules.  Is there a better way?

**Comment by garywiz** [comment]
I recommend doing the following:

For environment variables, include a "settings" section which declares any global environment variables:

    settings: {
       PATH: "/my/bin:$(PATH)",
       CONFIG_APPDIR: "/myapp",
    }

Then, for a start-up script, make it a "oneshot" script that is part of the "INIT" service group.  That will assure it starts before any other groups or services automatically:

    prepare_container.service: {
       type: oneshot,
       command: "/my/bin/setup_app",
       service_groups: "INIT",
    }

Essentially, have chaperone run your startup scripts separately, start your services, then it remains PID#1 in order to catch errors, etc.

That's the simplest way to get started.  By default, any output from your script will go to the syslog, so if you want to be sure you catch ALL syslogs (no matter where from), you can also include a logging section.  That will capture the stdout of any programs, as well as actual syslog data sent by any other processes:

    my_console.logging: {
      selector: "*.info",
      stdout: true,
   }

I typed those from memory, hopefully no mistakes there.  But, if you want to browse some working examples, just to see syntax and ideas, this is a good directory to browse in: https://github.com/garywiz/chaperone-docker/tree/master/baseimage/setup/apps/chaperone.d

Is that a good start?

**Comment by mc0e** [comment]
Yes, that did the trick nicely.
