### ISSUE TITLE
type forking and exit_fills true

### ISSUE THREAD

**Issue by JrCs** [garywiz/chaperone#4]
Hi,

i want to start a service that fork and want to kill the system if the service (which have a pid) die.
For example for my postfix service i use:
```
postfix.service: {
  type: forking,
  service_groups: IDLE,
  command: "postfix start",
  pidfile: /var/spool/postfix/pid/master.pid,
  after: "postgrey.service",
  exit_kills: true,
}
```
The problem is that the `postfix start` command start the postfix master process but return when it has fork the master process. So chaperone see that the `postfix start` end and kill the whole system (because of the exit_kills with value true) even if the pid is valid and the forking process is running.

EDIT the logs i have:
```
May 16 19:39:07 7f454733d6e4 chaperone[1]: system will be killed when '/usr/sbin/postfix' exits
May 16 19:39:07 7f454733d6e4 postfix-script[321]: starting the Postfix mail system
May 16 19:39:07 7f454733d6e4 master[323]: daemon started -- version 3.0.4, configuration /etc/postfix
May 16 19:39:07 7f454733d6e4 chaperone[1]: REAP pid=257,status=0
May 16 19:39:07 7f454733d6e4 chaperone[1]: REAP pid=0,status=0
May 16 19:39:07 7f454733d6e4 chaperone[1]: postfix.service exit status for pid=257 is '<ProcStatus exit_status=0>'
May 16 19:39:07 7f454733d6e4 chaperone[1]: Request made to kill system.
May 16 19:39:07 7f454733d6e4 chaperone[1]: postfix.service waiting for PID file: /var/spool/postfix/pid/master.pid
May 16 19:39:07 7f454733d6e4 chaperone[1]: postfix.service successfully started
May 16 19:39:07 7f454733d6e4 chaperone[1]: postfix.service notified waiters upon completion
May 16 19:39:15 7f454733d6e4 master[323]: terminating on signal 15
May 16 19:39:15 7f454733d6e4 chaperone[1]: no child processes present
May 16 19:39:15 7f454733d6e4 chaperone[1]: Final termination phase.
```

**Comment by garywiz** [comment]
What you're seeing is correct behavior at the moment.  `exit_kills` was intended to be used for something like a "bash" shell which should unconditionally terminate the entire container even if other things are running.  However, I see what you're getting at.  It could be a bit smarter about forking services. 

Even if you don't use `exit_kills`, chaperone *should* terminate the container when the last process quits automatically.  Do you have other processes running which are preventing the container from exiting?

**Comment by garywiz** [comment]
Chaperone 0.3.8 fixes this behavior so that type='forking' and type='notify' processes will wait until the spawned process terminates before killing the system, not the initial start-up (such as the postfix command).   Note that this will only work properly if you use a `pidfile` and if the pidfile is indeed created, as you do above.

The situation where a PID file is not created is considered an error in start-up, and therefore `exit_kills` will not be respected in that case.

However, with the above caveats, I believe the `exit_kills` now works the way you would have expected it to.

The new version is here on GitHub as well as Pypi so you can just update it with pip.

**Comment by JrCs** [comment]
Thanks @garywiz
