### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by ionelmc** [garywiz/chaperone#5]
Would you be interested in accepting PR with Python 2 support?

**Comment by garywiz** [comment]
I doubt that Python 2 support will be on the roadmap.   It was a difficult decision to pin Chaperone to Python 3, but once we made the decision, we began to realize how much P3 had to offer, and it's not quite entrenched in the code.  For example, we use the Python 3 `asyncio` features *extensively* for managing multiple tasks.  Without it, extensive rewrites as well as adding a requirement for Twisted (or some other async package), would be added to the list.  Moreover, we discovered that many modern distros (such as Docker base images) are omitting Python2 completely.

Is there a reason why Python2 support is important to you?  Specific platforms where Python3 does not run?  etc.?

If anything, we're considering do a version in "Go" so that Chaperone can become a completely stand-alone executable.

If you know anybody who would like to try such a backport, let me know, I may be willing to assist, but it would not be very easy.

**Comment by ionelmc** [comment]
I see, I thought the internals were much simpler :confused: 

I'm dockerizing a Python 2 app (it's a big messed up thing and porting to 3 would involve fixing inordinate amounts of incorrect text handling).

I could install py3 alongside ... just for Chaperone.

Is Chaperone using py3-only features (like `yield from`)? If not, it could use https://pypi.python.org/pypi/trollius

**Comment by garywiz** [comment]
Yes, exactly.   Chaperone uses Python 3 `yield from` as well as the `@coroutine` decorator extensively.  In fact, those features account for Chaperone's robustness at handing many tasks concurrently.  We are long-time Twisted users, and we've found the async features in Python 3 to be easier and more intuitive, and because they are built-in to Python3, no external libraries are required and we can rely upon it more easily.

You should be able to install Py3 and Py2 side by side.  The executables are created automatically by `pip` and it should automatically assure that they use the correct Python executable.

**Comment by ionelmc** [comment]
Alright, fine. Thanks for the explanations.
